<?php
/**
 * Created by PhpStorm.
 * User: Najam.Haque
 * Date: 11/7/2015
 * Time: 10:26 AM
 */
?>
<div class="bs-example">Search Result
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Rating</th>
        </tr>
        </thead>
        <tbody>
        <?php
        /**
         * Perhaps It would be even better to use partialLoop.
         * That will avoid a foreach
         */
        foreach ($this->hotels as $hotel) {
            echo $this->partial('hotel/partials/hotelRow.phtml', ['hotel' => $hotel]);
        }
        ?>
        </tbody>
    </table>
</div>
