<?php
/**
 * Created by PhpStorm.
 * User: Najam.Haque
 * Date: 11/7/2015
 * Time: 10:58 PM
 */
?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="/css/hotel/spinner.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="/js/hotel/AjaxCall.js"></script>
<form>
    <label for="ajaxProxy"> Proxy </label><input id="ajaxProxy" type="radio" name="ajaxType" value="/hotel/ajax/" checked="checked"><br />
    <label for="ajax3rdParty"> enable-cors.org </label><input id="ajax3rdParty" type="radio" name="ajaxType" value="http://enable-cors.org/server.html"><br />
    <label for="ajaxApi"> api.travelbrands.com </label><input id="ajaxApi" type="radio" name="ajaxType" value="http://api.travelbrands.com/interview-test/ajax.php"><br />
</form>
<p>
    <a id="btnAjaxCaller" class="btn btn-small btn-success has-spinner">
        <span class="spinner"><i class="icon-spin icon-refresh"></i></span>
        Click Here to make your Ajax Call
    </a>
    <a id="btnClearResponse" class="btn btn-small btn-success has-spinner">
        <span class="spinner"><i class="icon-spin icon-refresh"></i></span>
        Click Here reset the response from prev calls
    </a>
</p>
<div id="ajaxResult">Ajax Result will be displayed here</div>
